import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import NavbarPage from "@/components/layouts/Navbar";
import Sidebar from "@/components/layouts/Sidebar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gray-50`}>
        <NavbarPage />

        <div className="flex overflow-hidden bg-white pt-16">
          <Sidebar />
          <div className="absolute top-0 left-[17vw] w-[83vw] pt-20 pr-8">
            <div className="bg-white p-4 rounded-lg text-muted-foreground min-h-full">
            {children}
            </div>
          </div>
        </div>

        <Toaster />
      </body>
    </html>
  );
}
